on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch

name: 🚀 Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo publish --token ${{secrets.CRATES_TOKEN}}